packages:
  - "libs/**"
  - "domain/domain-core/*"
autoInstallPeers: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - "nx"
  - "prisma"
  - "unrs-resolver"
strictPeerDependencies: false
